name = "ChevLie"
uuid = "02962454-1d98-4bbc-b4d2-c6bfa4ecea97"
authors = ["Meinolf Geck\n <meinolf.geck@mathematik.uni-stuttgart.de>"]
version = "1.2.0"
[compat]
julia = "1"
BenchmarkTools = "1"
SparseArrays = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
